In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-2.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 11.0 MB/s eta 0:00:01
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     |████████████████████████████████| 341 kB 133.1 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     |████████████████████████████████| 502 kB 130.8 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2.8.2)
Collecting numpy>=1.20.3; python_version < "3.10"
  Downloading numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 116.0 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)
Installing collected packages: tzdata, pytz, numpy, pandas
  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.24.3 pandas-2.0.2 pytz-2023.3 tzdata-2023.3
Note: you may need to restart the kernel to use updated packages.

In [14]:
import pandas as pd
show_csv = pd.read_csv('/home/ubuntu/workspace/airline-passengers.csv',on_bad_lines='skip')
show_csv

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [17]:
data_pass=show_csv['Passengers']
data_pass

0      112
1      118
2      132
3      129
4      121
      ...
139    606
140    508
141    461
142    390
143    432
Name: Passengers, Length: 144, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
training, test = train_test_split(data_pass,test_size=0.2, random_state=42)#Nilai X training dan Nilai X testing
training

124    420
31     199
98     356
36     171
16     125
      ...
71     229
106    305
14     141
92     355
102    465
Name: Passengers, Length: 115, dtype: int64

In [27]:
#import modul
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score,  accuracy_score

In [33]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
scaled = scaler.fit_transform(training)
train = pd.DataFrame(scaled)
train

ValueError: Expected 2D array, got 1D array instead:
array=[420. 199. 356. 171. 125. 104. 306. 348. 230. 310. 559. 315. 204. 112.
 284. 172. 183. 317. 145. 150. 140. 505. 293. 209. 135. 306. 181. 114.
 259. 312. 508. 194. 199. 363. 270. 535. 162. 274. 390. 235. 606. 461.
 243. 135. 277. 318. 196. 166. 315. 146. 405. 148. 242. 203. 374. 278.
 396. 407. 136. 126. 340. 491. 129. 149. 193. 242. 360. 148. 422. 132.
 406. 264. 236. 404. 172. 347. 188. 461. 347. 472. 405. 218. 180. 413.
 196. 318. 548. 133. 211. 269. 184. 622. 201. 227. 463. 180. 178. 336.
 419. 118. 229. 362. 467. 348. 404. 313. 267. 342. 432. 158. 229. 305.
 141. 355. 465.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [37]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))

# Reshape the input data
reshaped_data = training.values.reshape(-1, 1)  # or reshape(1, -1) if it contains a single sample

scaled = scaler.fit_transform(reshaped_data)
train = pd.DataFrame(scaled)
train

            0
0    0.610039
1    0.183398
2    0.486486
3    0.129344
4    0.040541
..        ...
110  0.241313
111  0.388031
112  0.071429
113  0.484556
114  0.696911

[115 rows x 1 columns]

In [39]:
# Menambahkan nama kolom baru
kolom = ['Passengers'] # Ganti dengan nama kolom baru yang diinginkan
train.columns = kolom
train

     Passengers
0      0.610039
1      0.183398
2      0.486486
3      0.129344
4      0.040541
..          ...
110    0.241313
111    0.388031
112    0.071429
113    0.484556
114    0.696911

[115 rows x 1 columns]

ambil data t-3 , t-2,t-1 dan t

In [ ]:
df = pd.DataFrame()
df
type(df.iloc[0])
<class 'pandas.core.series.Series'>
df.iloc[0]

In [51]:
import numpy as np
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps
    # check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

# define univariate time series
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# transform to a supervised learning problem
X, y = split_sequence(scaled, 3)
print(X.shape, y.shape)
shapeX = np.reshape(X,(112, 3))
dfX = pd.DataFrame(shapeX,columns=["t-3","t-2","t-1"])
dfy = pd.DataFrame(y, columns=["t"])

df = pd.concat((dfX, dfy), axis = 1)
df

(112, 3, 1) (112, 1)

          t-3       t-2       t-1         t
0    0.610039  0.183398  0.486486  0.129344
1    0.183398  0.486486  0.129344  0.040541
2    0.486486  0.129344  0.040541  0.000000
3    0.129344  0.040541  0.000000  0.389961
4    0.040541  0.000000  0.389961  0.471042
..        ...       ...       ...       ...
107  0.459459  0.633205  0.104247  0.241313
108  0.633205  0.104247  0.241313  0.388031
109  0.104247  0.241313  0.388031  0.071429
110  0.241313  0.388031  0.071429  0.484556
111  0.388031  0.071429  0.484556  0.696911

[112 rows x 4 columns]