In [4]:
pip install pandas

Requirement already satisfied: pandas in /home/ubuntu/.local/lib/python3.8/site-packages (2.0.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (1.24.3)
Requirement already satisfied: pytz>=2020.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)
Note: you may need to restart the kernel to use updated packages.

Kelas PSD C

Ketua Kelompok
NIM :  200411100039
Nama : Amelia Nur Septiyasari

Anggota Kelompok
NIM : 200411100148
Nama : Fadilatul Jannah

Github Ketua : https://github.com/Amelia039/kolaborasipro

In [2]:
import pandas as pd
show_csv = pd.read_csv('/home/ubuntu/workspace/airline-passengers.csv',on_bad_lines='skip')
show_csv

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [3]:
data_pass=show_csv['Passengers']
data_pass

0      112
1      118
2      132
3      129
4      121
      ...
139    606
140    508
141    461
142    390
143    432
Name: Passengers, Length: 144, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
training, test = train_test_split(data_pass,test_size=0.2)#Nilai X training dan Nilai X testing
training

66     302
110    362
50     236
0      112
142    390
      ...
109    318
9      119
123    396
86     317
60     204
Name: Passengers, Length: 115, dtype: int64

In [5]:
#import modul
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score,  accuracy_score

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
scaled = scaler.fit_transform(training)
train = pd.DataFrame(scaled)
train

ValueError: Expected 2D array, got 1D array instead:
array=[209. 132. 242. 491. 315. 405. 243. 340. 140. 196. 359. 183. 146. 193.
 180. 172. 405. 336. 125. 347. 348. 548. 363. 235. 126. 218. 203. 145.
 201. 171. 310. 390. 121. 236. 129. 306. 622. 136. 135. 356. 270. 199.
 374. 148. 407. 508. 463. 461. 170. 149. 467. 391. 194. 118. 150. 181.
 267. 135. 229. 432. 277. 364. 472. 264. 178. 404. 163. 180. 269. 362.
 227. 148. 348. 318. 178. 606. 237. 112. 211. 172. 284. 264. 472. 230.
 313. 141. 305. 293. 413. 204. 318. 229. 342. 317. 355. 355. 235. 419.
 435. 119. 271. 170. 158. 306. 417. 505. 188. 196. 133. 162. 166. 233.
 229. 302. 420.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))

# Reshape the input data
reshaped_data = training.values.reshape(-1, 1)  # or reshape(1, -1) if it contains a single sample

scaled = scaler.fit_transform(reshaped_data)
train = pd.DataFrame(scaled)
train

            0
0    0.372549
1    0.490196
2    0.243137
3    0.000000
4    0.545098
..        ...
110  0.403922
111  0.013725
112  0.556863
113  0.401961
114  0.180392

[115 rows x 1 columns]

In [7]:
# Menambahkan nama kolom baru
kolom = ['training'] # Ganti dengan nama kolom baru yang diinginkan
train.columns = kolom
train

     training
0    0.372549
1    0.490196
2    0.243137
3    0.000000
4    0.545098
..        ...
110  0.403922
111  0.013725
112  0.556863
113  0.401961
114  0.180392

[115 rows x 1 columns]

ambil data t-3 , t-2,t-1 dan t

In [8]:
import numpy as np
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps
    # check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

# define univariate time series
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# transform to a supervised learning problem
X, y = split_sequence(scaled, 3)
print(X.shape, y.shape)
shapeX = np.reshape(X,(112, 3))
dfX = pd.DataFrame(shapeX,columns=["t-3","t-2","t-1"])
dfy = pd.DataFrame(y, columns=["t"])

data_train = pd.concat((dfX, dfy), axis = 1)
data_train

(112, 3, 1) (112, 1)

          t-3       t-2       t-1         t
0    0.372549  0.490196  0.243137  0.000000
1    0.490196  0.243137  0.000000  0.545098
2    0.243137  0.000000  0.545098  0.129412
3    0.000000  0.545098  0.129412  0.245098
4    0.545098  0.129412  0.245098  0.154902
..        ...       ...       ...       ...
107  0.476471  0.394118  0.115686  0.403922
108  0.394118  0.115686  0.403922  0.013725
109  0.115686  0.403922  0.013725  0.556863
110  0.403922  0.013725  0.556863  0.401961
111  0.013725  0.556863  0.401961  0.180392

[112 rows x 4 columns]

In [10]:
data_train_X = data_train.drop(columns=['t'])
data_train_X

          t-3       t-2       t-1
0    0.372549  0.490196  0.243137
1    0.490196  0.243137  0.000000
2    0.243137  0.000000  0.545098
3    0.000000  0.545098  0.129412
4    0.545098  0.129412  0.245098
..        ...       ...       ...
107  0.476471  0.394118  0.115686
108  0.394118  0.115686  0.403922
109  0.115686  0.403922  0.013725
110  0.403922  0.013725  0.556863
111  0.013725  0.556863  0.401961

[112 rows x 3 columns]

In [12]:
data_train_Y = data_train['t'].values
data_train_Y

array([0.        , 0.54509804, 0.12941176, 0.24509804, 0.15490196,
       0.05686275, 0.51372549, 0.06470588, 0.23921569, 0.22941176,
       0.45098039, 0.04509804, 0.06666667, 0.22941176, 0.24117647,
       0.57647059, 0.40392157, 0.82941176, 0.25686275, 0.14901961,
       0.13333333, 0.14117647, 0.19019608, 0.30980392, 0.15882353,
       1.        , 0.68431373, 0.39215686, 0.96862745, 0.1745098 ,
       0.74313725, 0.04705882, 0.11372549, 0.31176471, 0.05490196,
       0.39803922, 0.31764706, 0.49411765, 0.07058824, 0.29803922,
       0.01764706, 0.25490196, 0.01176471, 0.39803922, 0.70588235,
       0.38039216, 0.01176471, 0.3254902 , 0.19411765, 0.57843137,
       0.60392157, 0.60784314, 0.09019608, 0.09803922, 0.00588235,
       0.57254902, 0.13529412, 0.25490196, 0.07058824, 0.13333333,
       0.77647059, 0.59019608, 0.1       , 0.70588235, 0.0254902 ,
       0.46078431, 0.77058824, 0.12941176, 0.46078431, 0.24117647,
       0.48431373, 0.17058824, 0.04117647, 0.2372549 , 0.4627451 ,
       0.47647059, 0.35490196, 0.38823529, 0.28823529, 0.85490196,
       0.4627451 , 0.54705882, 0.23137255, 0.11372549, 0.59803922,
       0.13921569, 0.03921569, 0.16078431, 0.32352941, 0.03333333,
       0.31372549, 0.62745098, 0.48627451, 0.63333333, 0.10588235,
       0.47843137, 0.3372549 , 0.87647059, 0.68823529, 0.20784314,
       0.38039216, 0.49215686, 0.30392157, 0.44705882, 0.47647059,
       0.39411765, 0.11568627, 0.40392157, 0.01372549, 0.55686275,
       0.40196078, 0.18039216])

In [15]:
from sklearn.preprocessing import MinMaxScaler
import joblib

scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(data_train_X)
features_names = data_train_X.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features

          t-3       t-2       t-1
0    0.372549  0.490196  0.243137
1    0.490196  0.243137  0.000000
2    0.243137  0.000000  0.545098
3    0.000000  0.545098  0.129412
4    0.545098  0.129412  0.245098
..        ...       ...       ...
107  0.476471  0.394118  0.115686
108  0.394118  0.115686  0.403922
109  0.115686  0.403922  0.013725
110  0.403922  0.013725  0.556863
111  0.013725  0.556863  0.401961

[112 rows x 3 columns]

DATA TESTING

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))

# Reshape the input data
reshaped_data = test.values.reshape(-1, 1)  # or reshape(1, -1) if it contains a single sample

scaled = scaler.fit_transform(reshaped_data)
test = pd.DataFrame(scaled)
test

           0
0   0.344353
1   0.440771
2   0.272727
3   0.187328
4   0.126722
5   0.641873
6   1.000000
7   0.994490
8   0.553719
9   0.253444
10  0.027548
11  0.253444
12  0.187328
13  0.123967
14  0.710744
15  0.085399
16  0.338843
17  0.454545
18  0.867769
19  0.829201
20  0.983471
21  0.542700
22  0.261708
23  0.000000
24  0.826446
25  0.366391
26  0.829201
27  0.060606
28  0.639118

In [17]:
kolom = ['Testing']
train.columns = kolom
train

      Testing
0    0.372549
1    0.490196
2    0.243137
3    0.000000
4    0.545098
..        ...
110  0.403922
111  0.013725
112  0.556863
113  0.401961
114  0.180392

[115 rows x 1 columns]

In [19]:
# import numpy as np
# from numpy import array
# # split a univariate sequence into samples
# def split_(sequence, n_steps):
#   X, y = list(), list()
#   for i in range(len(sequence)):
#     # find the end of this pattern
#     end_ix = i + n_steps
#     # check if we are beyond the sequence
#     if end_ix > len(sequence)-1:
#       break
#     # gather input and output parts of the pattern
#     seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
#     X.append(seq_x)
#     y.append(seq_y)
#   return array(X), array(y)

# # define univariate time series
# series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# # transform to a supervised learning problem
# X, y = split_sequence(scaled, 3)
# print(X.shape, y.shape)
# shapeX = np.reshape(X,(26, 3))
# dfX = pd.DataFrame(shapeX,columns=["t-3","t-2","t-1"])
# dfy = pd.DataFrame(y, columns=["t"])

# data_test = pd.concat((dfX, dfy), axis = 1)
# data_test

(26, 3, 1) (26, 1)

         t-3       t-2       t-1         t
0   0.344353  0.440771  0.272727  0.187328
1   0.440771  0.272727  0.187328  0.126722
2   0.272727  0.187328  0.126722  0.641873
3   0.187328  0.126722  0.641873  1.000000
4   0.126722  0.641873  1.000000  0.994490
5   0.641873  1.000000  0.994490  0.553719
6   1.000000  0.994490  0.553719  0.253444
7   0.994490  0.553719  0.253444  0.027548
8   0.553719  0.253444  0.027548  0.253444
9   0.253444  0.027548  0.253444  0.187328
10  0.027548  0.253444  0.187328  0.123967
11  0.253444  0.187328  0.123967  0.710744
12  0.187328  0.123967  0.710744  0.085399
13  0.123967  0.710744  0.085399  0.338843
14  0.710744  0.085399  0.338843  0.454545
15  0.085399  0.338843  0.454545  0.867769
16  0.338843  0.454545  0.867769  0.829201
17  0.454545  0.867769  0.829201  0.983471
18  0.867769  0.829201  0.983471  0.542700
19  0.829201  0.983471  0.542700  0.261708
20  0.983471  0.542700  0.261708  0.000000
21  0.542700  0.261708  0.000000  0.826446
22  0.261708  0.000000  0.826446  0.366391
23  0.000000  0.826446  0.366391  0.829201
24  0.826446  0.366391  0.829201  0.060606
25  0.366391  0.829201  0.060606  0.639118

In [21]:
data_test_X = data_test.drop(columns=['t'])
data_test_X

         t-3       t-2       t-1
0   0.344353  0.440771  0.272727
1   0.440771  0.272727  0.187328
2   0.272727  0.187328  0.126722
3   0.187328  0.126722  0.641873
4   0.126722  0.641873  1.000000
5   0.641873  1.000000  0.994490
6   1.000000  0.994490  0.553719
7   0.994490  0.553719  0.253444
8   0.553719  0.253444  0.027548
9   0.253444  0.027548  0.253444
10  0.027548  0.253444  0.187328
11  0.253444  0.187328  0.123967
12  0.187328  0.123967  0.710744
13  0.123967  0.710744  0.085399
14  0.710744  0.085399  0.338843
15  0.085399  0.338843  0.454545
16  0.338843  0.454545  0.867769
17  0.454545  0.867769  0.829201
18  0.867769  0.829201  0.983471
19  0.829201  0.983471  0.542700
20  0.983471  0.542700  0.261708
21  0.542700  0.261708  0.000000
22  0.261708  0.000000  0.826446
23  0.000000  0.826446  0.366391
24  0.826446  0.366391  0.829201
25  0.366391  0.829201  0.060606

In [22]:
data_test_Y = data_test['t'].values
data_test_Y

array([0.18732782, 0.12672176, 0.64187328, 1.        , 0.99449036,
       0.55371901, 0.25344353, 0.02754821, 0.25344353, 0.18732782,
       0.12396694, 0.7107438 , 0.08539945, 0.33884298, 0.45454545,
       0.8677686 , 0.8292011 , 0.98347107, 0.54269972, 0.26170799,
       0.        , 0.82644628, 0.36639118, 0.8292011 , 0.06060606,
       0.63911846])

KNN

In [24]:
from sklearn import neighbors
regresor = neighbors.KNeighborsRegressor(n_neighbors = 3)
regresor.fit(training, data_train_Y)

ValueError: Expected 2D array, got 1D array instead:
array=[302 362 236 112 390 178 237 191 141 374 145 234 229 342 135 146 229 235
 406 318 535 243 188 180 184 209 270 193 622 461 312 606 201 491 136 170
 271 140 315 274 364 148 264 121 242 118 315 472 306 118 278 211 407 420
 422 158 162 115 404 181 242 148 180 508 413 163 472 125 347 505 178 347
 235 359 199 133 233 348 355 293 310 259 548 348 391 230 170 417 183 132
 194 277 129 272 432 360 435 166 356 284 559 463 218 306 363 267 340 355
 313 171 318 119 396 317 204].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [37]:
pred_test = regresor.predict(test)
pred_test

array([0.20196078, 0.28235294, 0.34640523, 0.33006536, 0.14705882,
       0.26797386, 0.26078431, 0.16339869, 0.22941176, 0.5248366 ,
       0.44640523, 0.15882353, 0.19346405, 0.30915033, 0.44771242,
       0.24771242, 0.24901961, 0.15555556, 0.24313725, 0.22810458,
       0.22941176, 0.1751634 , 0.54444444])

In [38]:
from sklearn.metrics import mean_squared_error 
from math import sqrt
error = sqrt(mean_squared_error(test_label,pred_test))
error

0.2955950076597719